services:
  - type: web
    name: backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://alchemist:2kX8FNPzloQELdSD5GYCJC2q3Bnqcqnb@dpg-d16hp66mcj7s73c5m5e0-a.oregon-postgres.render.com/electronics_catalogs
      - key: PORT
        value: 5002 # 🔧 Optional, but keeps port consistent

  - type: web
    name: frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    envVars:
      - key: NODE_ENV
        value: production
      - key: REACT_APP_API_URL
        value: https://ars-commercess.onrender.com
